export const SET_PAGE_CONF = 'SET_PAGE_CONF';

export const GET_PAGE_DATA_REQUEST = 'GET_PAGE_DATA_REQUEST';
export const GET_PAGE_DATA_SUCCESS = 'GET_PAGE_DATA_SUCCESS';
export const GET_PAGE_DATA_FAILURE = 'GET_PAGE_DATA_FAILURE';

export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';
export const CREATE_MENU = 'CREATE_MENU';

export const FOLLOWS_OPEN = 'FOLLOWS_OPEN';
export const FOLLOWS_CLOSE = 'FOLLOWS_CLOSE';
export const FOLLOWS_REQUEST = 'FOLLOWS_REQUEST';
export const FOLLOWS_SUCCESS = 'FOLLOWS_SUCCESS';
export const FOLLOWS_FAILURE = 'FOLLOWS_FAILURE';

export const PHOTOVIEW_OPEN = 'PHOTOVIEW_OPEN';
export const PHOTOVIEW_CLOSE = 'PHOTOVIEW_CLOSE';
export const PHOTOVIEW_REQUEST = 'PHOTOVIEW_REQUEST';
export const PHOTOVIEW_SUCCESS = 'PHOTOVIEW_SUCCESS';
export const PHOTOVIEW_FAILURE = 'PHOTOVIEW_FAILURE';

export const GET_PANEL_POSTS_REQUEST = 'GET_PANEL_POSTS_REQUEST';
export const GET_PANEL_POSTS_SUCCESS = 'GET_PANEL_POSTS_SUCCESS';
export const GET_PANEL_POSTS_FAILURE = 'GET_PANEL_POSTS_FAILURE';

export const GET_SEARCH_USERS_REQUEST = 'GET_SEARCH_USERS_REQUEST';
export const GET_SEARCH_USERS_SUCCESS = 'GET_SEARCH_USERS_SUCCESS';
export const GET_SEARCH_USERS_FAILURE = 'GET_SEARCH_USERS_FAILURE';